name: Preflight-Checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jira-id-validate:
    name: jira id validate
    uses: nice-cxone/github-actions-shared/.github/workflows/validate-jira-id.yaml@master
    secrets: inherit

  sonarqube-code-analysis:
    name: Sonarqube Code Analysis
    uses: nice-cxone/github-actions-shared/.github/workflows/node-pr-sonar-scan.yaml@master
    secrets: inherit

  deploy:
    name: Web Preflight Checks
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::369498121101:role/nice-devops-github-role'
          aws-region: us-west-2

      - name: Copy files to the test website with the AWS CLI
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nice-devops --domain-owner 369498121101 --query authorizationToken --output text`
          touch ~/.npmrc
          echo "registry=https://nice-devops-369498121101.d.codeartifact.us-west-2.amazonaws.com/npm/cxone-npm/" > ~/.npmrc
          echo "//nice-devops-369498121101.d.codeartifact.us-west-2.amazonaws.com/npm/cxone-npm/:always-auth=true" >> ~/.npmrc
          echo "//nice-devops-369498121101.d.codeartifact.us-west-2.amazonaws.com/npm/cxone-npm/:_authToken=${CODEARTIFACT_AUTH_TOKEN}" >> ~/.npmrc

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          npm ci

      - name: Linting
        run: |
          ###########
          # Validate the linting rules are honored
          ###########
          npm run lint
      - name: Unit Tests
        run: |
          ###########
          # Validate the linting rules are honored
          ###########
          npm run test

      - name: Build Prod
        run: |
          ###########
          # Build Code and Run Test Cases
          ###########
          npm run build-prod
